### ISSUE TITLE
Evolution : champ de fusion pour emailing

### ISSUE THREAD

**Issue by bastienho** [wyde22/cdn-tax-receipt-france#4]
En début d'année, il est utile d'envoyer un mailing en publipostage pour indiquer la somme à renseigner dans la déclaration d'import pour l'année précédente.

Un champ de fusion `tax_receipt_amount_n1` à intégrer dans les mailing pour obtenir la somme des contributions eligible de l'année N-1 serait donc utile.

## Proposition:

Ajouter des **Custom Fields**  `tax_receipt_amount_n0` et `tax_receipt_amount_n1` qui afficheraient les montant pour l'année en cours et l'année précédente.

L'info serait donc affiché dans la fiche de contact et utilisable dans les champs de fusion.

## TODO:
- [ ] Ajout des custom fields via l'upgrader
- [ ] Création d'une fonction de calcul de la somme de montant de reçus fiscaux prenant comme paramètre une année
- [ ] Création des fonctions de callback pour les custom fields

**Comment by wyde22** [comment]
j'ai inspecté le code du module pour cette partie et il y a déjà cette fonctionnalité. Le calcul de la somme des montants des reçus fiscaux se fait correctement dans le fichier `cdntaxreceiptsfr.functions.inc` ligne 1098. Cela fonctionne bien avec l'option developer du module (émission du reçu fiscal avec TCPDF). Mais cela ne fonctionne pas avec l'option ajoutée par mes soins soit en utilisant un template de message.

Je suis en train de voir comment adapter mon code pour que cela fonctionne pour tous les cas
